### ISSUE TITLE
如何安装

### ISSUE THREAD

**Issue by z-3zh** [fcitx-contrib/fcitx5-hallelujah#3]
请问如何安装

**Comment by Renkai** [comment]
https://github.com/fcitx-contrib/fcitx5-hallelujah/blob/master/.github/workflows/ci.yml
这里应该是Ubuntu下的安装方法, 不过我试了试mac下安装没成功, 很多库没有. 借楼追问, 如何在mac下安装.

**Comment by eagleoflqj** [comment]
Linux需要按这个仓库的ci脚本构建安装。
mac小企鹅的话，ci在https://github.com/fcitx-contrib/fcitx5-macos-plugins/blob/master/.github/workflows/ci.yml ，不过不需要自行构建，可以用插件管理器安装。
