### ISSUE TITLE
Cursor following and phrase/sentence prediction

### ISSUE THREAD

**Issue by rayliou** [fcitx-contrib/fcitx5-hallelujah#4]
Thanks to the author for developing such a great word correction input method. At the moment, it seems that it would be more useful to include the following two features
- Cursor following: When typing, the cursor jumps to a position far away from the current input point in the prediction box, which is quite distracting. It would be nice if it could be adjusted to keep the input point constant.
- The second function is a bit more advanced, that is, it can predict more phrases and sentences, in fact, it mainly predicts phrase collocation, word pattern variation, and so on.

**Comment by eagleoflqj** [comment]
> Cursor following

With https://github.com/fcitx-contrib/fcitx5-hallelujah/pull/6 you may hide translation and IPA so that the width of candidate window is limited.

> predict

There is no such feature in the original HallelujahIM so there is nothing that can be ported here.
